#!/bin/sh
mount -t devtmpfs devtmpfs /dev
mount -t sysfs sysfs /sys
mount -t proc proc /proc
dmesg -n 1
echo "Mounting real root..."
mount -t tmpfs tmpfs /tmp
mkdir /tmp/upper /tmp/work
mount -t auto `findfs LABEL=iqOS` /mnt/boot
mount -t squashfs /mnt/boot/fs.squash /mnt/roroot
mount -t overlay overlay -olowerdir=/mnt/roroot,upperdir=/tmp/upper,workdir=/tmp/work /mnt/root
exec switch_root /mnt/root /init
